# Docker Compose file for Production

version: '3.9'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  APPLE_APPLICATION_IDENTIFIER: ${APPLE_APPLICATION_IDENTIFIER}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

services:
  app:
    image: yessetmurat/fracker:latest
    environment:
      <<: *shared_environment
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '443:443'
  db:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    ports:
      - '5432:5432'
